# Generated by Django 4.1.4 on 2022-12-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Building',
            new_name='Packages',
        ),
    ]
