# Generated by Django 4.1.4 on 2022-12-07 15:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0003_rename_name_packages_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='country',
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
    ]
