# Generated by Django 4.1.4 on 2022-12-07 15:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0004_alter_packages_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
