# Generated by Django 4.1.4 on 2022-12-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0006_alter_packages_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
