# Generated by Django 4.1.4 on 2022-12-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0007_alter_packages_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
