# Generated by Django 4.1.4 on 2022-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0008_alter_packages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
