# Generated by Django 4.1.4 on 2022-12-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0009_alter_packages_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caurosel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('decription', models.TextField()),
                ('book', models.CharField(max_length=100)),
            ],
        ),
    ]
