# Generated by Django 4.1.4 on 2022-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0010_caurosel1'),
    ]

    operations = [
        migrations.AddField(
            model_name='caurosel1',
            name='images',
            field=models.ImageField(default='exit', upload_to='imgs'),
            preserve_default=False,
        ),
    ]
