# Generated by Django 4.1.4 on 2022-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0011_caurosel1_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ladyimage', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='caurosel1',
            name='images',
            field=models.ImageField(upload_to='img'),
        ),
    ]
