# Generated by Django 4.1.4 on 2022-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0013_destination_delete_about_delete_caurosel1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
