# Generated by Django 4.1.4 on 2022-12-09 20:16

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0014_alter_packages_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
