# Generated by Django 4.1.4 on 2022-12-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0015_alter_packages_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='countries',
            field=models.CharField(max_length=100),
        ),
    ]
