# Generated by Django 4.1.4 on 2022-12-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0017_alter_packages_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_guides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('images1', models.ImageField(upload_to='im')),
            ],
        ),
    ]
