# Generated by Django 4.1.4 on 2022-12-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0018_tour_guides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images2', models.ImageField(upload_to='ib')),
                ('testimony', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.TextField()),
            ],
        ),
    ]
